### ISSUE TITLE
método DirectorActions.removeStudent não está removendo o estudante

### ISSUE THREAD

**Issue by micheldrv** [andrewmatheus/fs-challenge-squad-school-admin#38]
Na linha 346 da DirectorActions.java
`students.remove(StudentId - 1);`
está removendo direto da lista.

Esta lista utiliza o método `StudentsData.getAllStudents()` que eu alterei para retornar uma cópia da lista, ao invés da lista em si.
Por isso essa remoção não atualiza a lista propriamente dita.

Testei isso na DirectorActionTests e realmente, tentar remover um estudante não o remove.

Sugiro utilizar o método `StudentsData.removeStudent()` que no momento não está sendo utilizado.

**Comment by andrewmatheus** [comment]
feito na branch do review
